services:
  postgres:
    image: postgres:latest  
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
      POSTGRES_DB: fitness_db
    ports:
      - "5434:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    restart: unless-stopped  

volumes:
  postgres_data:  