services:
  postgres:
    image: postgres:15  
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password  
      POSTGRES_DB: fitness_db  
    volumes:
      - ./data:/var/lib/postgresql/data 
      - ./init:/docker-entrypoint-initdb.d 
    ports:
      - "5434:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clubs_network

networks:
  clubs_network:
    driver: bridge