services:
  postgres:
    image: postgres:15  # Используем официальный образ PostgreSQL версии 15
    container_name: fitness_postgres
    environment:
      POSTGRES_USER: fitness_user        # Имя пользователя базы данных
      POSTGRES_PASSWORD: fitness_password  # Пароль пользователя (замените на свой)
      POSTGRES_DB: fitness_db           # Имя базы данных
    volumes:
      - ./data:/var/lib/postgresql/data  # Персистентное хранилище данных
      - ./init:/docker-entrypoint-initdb.d  # Директория для скриптов инициализации
    ports:
      - "5434:5432"  # Порт для подключения к базе данных
    restart: unless-stopped  # Перезапуск контейнера при сбоях, кроме явной остановки
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fitness_user -d fitness_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - clubs_network

networks:
  clubs_network:
    driver: bridge